<?php

namespace AppBundle\Repository;

/**
 * GuestCollectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestCollectiveRepository extends \Doctrine\ORM\EntityRepository
{
}
