backend:
    resource:   "@BackendBundle/Resources/config/routing.yml"
    prefix:     /backend

app:
    resource:   "@AppBundle/Resources/config/routing.yml"
    prefix:     /
    options:
        expose: true

fos_user:
    resource:   "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:     /backend

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
