backend:
    resource:   "@BackendBundle/Resources/config/routing.yml"
    prefix:     /backend

app:
    resource:   "@AppBundle/Resources/config/routing.yml"
    prefix:     /

fos_user:
    resource:   "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:     /backend
